### ISSUE TITLE
ImportError: No module named 'pypandoc'

### ISSUE THREAD

**Issue by Markus00000** [avinassh/haxor#15]
When installing `haxor` I get this error:

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-install-zl_kpo7s/haxor/setup.py", line 6, in <module>
        import pypandoc
    ImportError: No module named 'pypandoc'

The error won’t occur if I install `pypandoc` before `haxor`.

The project’s `requirements-dev.txt` contains `pypandoc` but `requirements.txt` does not. Is this intended?

**Comment by avinassh** [comment]
nope, this is not intended. let me look into it. 

pypandoc is required only when you are doing some development work, like you want to send a patch or add a new feature.

**Comment by avinassh** [comment]
I am not able to reproduce the error. Can you tell me how did you try to install? I just did:

```bash
pip install haxor
```

and it worked fine

**Comment by Markus00000** [comment]
Sorry, I can’t reliably reproduce it.

If I remember correctly, it has only ever happened on the server (not locally) where I install it in a script from a requirements.txt (`pip install --upgrade --requirement "$requirements"`). If I manage to reproduce the issue, I will let you know. Right now, it installed correctly and I have no idea why it didn’t before. I haven’t made any related changes to the source, so I assume the cause lies in the server environment or deployment script.

**Comment by avinassh** [comment]
Sure, no problem ^_^
