### ISSUE TITLE
Update requests dependency

### ISSUE THREAD

**Issue by Markus00000** [avinassh/haxor#16]
Is it possible to make haxor support requests>=2.4.0 to solve this dependency conflict I have?

> haxor 1.1 has requirement requests==2.0.0, but you'll have requests 2.18.4 which is incompatible.

**Comment by avinassh** [comment]
sure! send a PR instead?

**Comment by avinassh** [comment]
pin it to 2.4.0

**Comment by svermeulen** [comment]
Why was this pinned instead of making it `>=2.4.0` ?  I'm having an issue with another package that has requests set to `>=2.6.0`
