### ISSUE TITLE
TimeoutError Top Stories

### ISSUE THREAD

**Issue by eotp** [avinassh/haxor#19]
Calling `https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty` from within the browser works fine, however if I try to leverage your wrapper 

    hn = HackerNews()
    top_stories = hn.top_stories()
    top_stories

I´ll run into `ProtocolError: ('Connection aborted.', TimeoutError(10060,...)` for most of the time.

Any hints? 
Thanks.

**Comment by avinassh** [comment]
Closing this issue, I just tested and it works as expected.
