### ISSUE TITLE
can we update the requests version?

### ISSUE THREAD

**Issue by deleted-123** [avinassh/haxor#25]
it messes with some of my other packages

**Comment by avinassh** [comment]
Yes, you can. I will push it to pypi later

**Comment by Mr-Steal-Your-Script** [comment]
@avinassh May you push to PyPi now? I kind of need your amazing package for a project and forking it to make small changes would be a bit unneeded :)

**Comment by avinassh** [comment]
@Mr-Steal-Your-Script hey, I published latest master to PyPI
