### ISSUE TITLE
Speeding up performance?

### ISSUE THREAD

**Issue by donnemartin** [avinassh/haxor#4]
Hi avinassh,

I'm running into performance issues running the examples.  It seems the HN API route can be considerably slower than just screen scraping.  

Is there a way for me to speed this up?  I wonder if the connection to Firebase is being reused--seems like with `requests` this should be done automatically?

Using `timeit` here are my results:

```
for story_id in hn.top_stories(limit=10):
    print hn.get_item(story_id)
```

`timei`t: 4.0882999897 sec

```
who_is_hiring = hn.get_item(8394339)

for comment_id in who_is_hiring.kids:
    comment = hn.get_item(comment_id)
    if 'python' in comment.text.lower():
        print comment.item_id
```

`timeit`: 125.318946123 sec

Thanks!

**Comment by donnemartin** [comment]
This seems to help significantly, cuts who_is_hiring by half:

```
def __init__(self, version='v0'):
    self.session = requests.Session()
    ...

def _get(self, url):
    response = self.session.get(url)
    ...
```

**Comment by avinassh** [comment]
@donnemartin Thanks for filing the issue. I will look into it. Please give me some time.

>  I wonder if the connection to Firebase is being reused--seems like with requests this should be done automatically?

No, it is not being reused. But may I know why it would be needed? Since we are not using any authentication or adding some extra headers etc

I am really surprised performance got better when you used sessions. So I need to look why.

**Comment by donnemartin** [comment]
@avinassh the Firebase HN API is pretty clunky.  For example with this code snippet:

```
for story_id in hn.top_stories(limit=10):
    print hn.get_item(story_id)
```

The first line will fire off a request to Firebase and get back a list of `story_id`.

The second line will fire off a request for each `story_id`.  If connections are not reused there is time spent creating a new connection for every `story_id`.

With the `who_is_hiring` snippet it's especially slow because you have to make a request for the story and one request for each comment (there are many comments).

**Comment by donnemartin** [comment]
> the Firebase HN API is pretty clunky

Here's a reference link:

https://github.com/HackerNews/API#design

I wish it were more like other APIs where calling something like  https://hacker-news.firebaseio.com/v0/topstories would actually list data about the top stories, paginated.  Instead, it just lists story ids and you have to make more requests to actually get the story data.

**Comment by avinassh** [comment]
I completely forgot about this, my apologies 😬 I have [updated](https://github.com/avinassh/haxor/releases/tag/0.5) it to start using Requests sessions and performance should be better now. 

I will update this lib again and start using Python asyncio for even better performance. Thank you!

**Comment by avinassh** [comment]
> I wish it were more like other APIs where calling something like https://hacker-news.firebaseio.com/v0/topstories would actually list data about the top stories, paginated. Instead, it just lists story ids and you have to make more requests to actually get the story data.

I will make these changes

**Comment by robertjkeck2** [comment]
@avinassh I see you have a branch for this update that hasn't had a PR submitted yet.  I went ahead and forked the project, implemented very simple async functionality, and a few other features.  Would you like me to submit a PR or hold off while you're working on your async branch?

**Comment by robertjkeck2** [comment]
Thoughts on closing this issue @avinassh ?

**Comment by avinassh** [comment]
Yup, we can close this now 😃
